# Generated by Django 6.0.1 on 2026-01-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='availability',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='parkingspot',
            index=models.Index(fields=['parking_lot', 'availability'], name='spot_lot_avail_idx'),
        ),
    ]
